apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberexp-app
  namespace: cyberexpert
  labels:
    app: cyberexp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyberexp-app
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cyberexp-app-preprod
    spec:
      containers:
      - name: cyberexp-app-preprod
        image: bclavijo110430/cyberexpress:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: cyberexp-app-preprod
spec:
  type: NodePort
  ports:  
     - port: 8000
       nodePort: 32203

  selector:
    app: cyberexp-app-preprod

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: cyberexp-app
#spec:
#  selector:
#    app: cyberexp-app
#  ports:
#    - port: 8000
#      targetPort: 8000
#  type: LoadBalancer   
