apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - create_namespace.yml
  - deployment.yml

images:
- name: gcr.io/PROJECT_ID/IMAGE
  newName: gcr.io/$PROJECT_ID/$IMAGE
  newTag: $GITHUB_SHA