name: Publish Docker image
on:
  push:
    tags:
      - "v*.*.*"
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag  bclavijo110430/cyberexpress:${{ env.RELEASE_VERSION }}
    - name: Push the tagged Docker image
      run: docker push bclavijo110430/cyberexpress:${{ env.RELEASE_VERSION }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag bclavijo110430/cyberexpress:latest
    - name: Push the latest Docker imag
      run: docker push bclavijo110430/cyberexpress:latest
      
    - name: Start Deployment
      #uses: actions/checkout@v1    
      uses: wshihadeh/docker-deployment-action@v1
      with:
           remote_docker_host: root@157.245.132.1
           ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
           ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
           deployment_mode: docker-compose
           copy_stack_file: true
           deploy_path: /stacks/service
           stack_file_name: docker-compose.yaml
           pull_images_first: true
           keep_files: 3
           args: -p test up -d

