name: Publish Docker image
#on:
#  push:
#    tags:
#      - "v*.*.*"
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag  bclavijo110430/cyberexpress:${{ env.RELEASE_VERSION }}
    - name: Push the tagged Docker image
      run: docker push bclavijo110430/cyberexpress:${{ env.RELEASE_VERSION }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag bclavijo110430/cyberexpress:latest
    - name: Push the latest Docker imag
      run: docker push bclavijo110430/cyberexpress:latest
      
    
     
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    #- name: Replace Environment Variables
     # uses: danielr1996/envsubst-action@1.0.0
    #  env:
  #        PORT: ${{ secrets.PORT }}
    #      DB_HOST: ${{ secrets.DB_HOST }}
    #      DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #      DB_PORT: ${{ secrets.DB_PORT }}
    #      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
   #       DB_NAME: ${{ secrets.DB_NAME }}
   #   with:
    #      input: deployment.yml
    #      output: deploy.yml

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
      env: 
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
    - name: Deploy to Kubernetes
      run: kubectl apply -f manifest/deployment.yml

    - name: Verify deployment
      run: kubectl rollout status deployment/cyberexp-app