name: Docker Image CI
on:
 release:
  types: [published]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag  bclavijo110430/cyberexpress:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push bclavijo110430/cyberexpress:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag bclavijo110430/cyberexpress:latest
    - name: Push the latest Docker image
      run: docker push bclavijo110430/cyberexpress:latest
      
    - name: Deploy to Heroku #set the whatever name you want to this step
      id: heroku
      uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
      with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: './docker-compose.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"bclavijo110430/cyberexpress:latest":"app1","cicdprueba":"app1","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type

