# Este flujo de trabajo usa acciones que no GitHub no certifica.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# en línea.

# GitHub recomienda anclar acciones a un SHA de confirmación.
# Para obtener una versión más reciente, debes actualizar el SHA.
# También puedes hacer referencia a una etiqueta o rama, pero la acción puede cambiar sin ninguna advertencia.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
 # PROJECT_ID: ${{ secrets.PROJECT_ID}} #id proyecto 
 # GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}  #nombre de cluster
 # GKE_ZONE: ${{ secrets.GKE_ZONE }}   # Add your cluster zone here.
  DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }} # Add your deployment name here.
  IMAGE: ${{ vars.IMAGE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: prodgke

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: auth google 
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
       credentials_json: ${{ secrets.GKE_SA_KEY }}

       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ vars.GKE_CLUSTER }}
        location: ${{ vars.GKE_ZONE }}
 #       project_id: ${{ secrets.GKE_PROJECT }}
 #       credentials: ${{ secrets.GKE_SA_KEY }}


    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          --file ./Dockerfile

#    # Push the Docker image to Google Container Registry
#    - name: Publish
#      run: |-
#        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
#
#    # Set up kustomize
#    - name: Set up Kustomize
#      run: |-
#        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
#        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
#    - name: Deploy
#      run: |-
#        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA --path ./kustomize
#        ./kustomize build . | kubectl apply -f -
#        kubectl rollout status deployment/$DEPLOYMENT_NAME
#        kubectl get services -o wide